package br.com.negocio;

import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import javax.faces.bean.ManagedBean;

import br.com.beans.Pessoa;
import br.com.persistencia.PessoaDao;

@ManagedBean(name= "pessoaBeans")
public class PessoaCtrl implements Serializable {

	private static final long serialVersionUID = 7329427687235074332L;
	private Pessoa pessoa = new Pessoa();
	private String filtro;
	
	public List<Pessoa> getListagem() {
		if(filtro == null){
			pessoa = new Pessoa();
			return PessoaDao.listagem(null);
		}else
		return PessoaDao.listagem(filtro);
	}
	public String actionGravar() {
		if (pessoa.getPes_id() == 0) {
			PessoaDao.salvar(pessoa);
			return "lista_cliente";
		} else {
			PessoaDao.alterar(pessoa);
			return "lista_cliente";
		}
	}
	
	public String actionVoltar() {
		pessoa = new Pessoa();
		return "index";

	}
	
	public String actionExcluir() {
		PessoaDao.excluir(pessoa);
		return "lista_cliente";

	}
	
	public String actionAlterar(Pessoa p) {
		pessoa = p;
		return "pessoa_cad";

	}
	
	
	
	
	
	//getters e setters
	public Pessoa getPessoa() {
		return pessoa;
	}
	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}
	public String getFiltro() {
		return filtro;
	}
	public void setFiltro(String filtro) {
		this.filtro = filtro;
	}
	
	//teste
	
	public String favColor1;
	public String favColor2;
	public String favColor3;

	//getter and setter methods

	//Generated by Map
	private static Map<String,Object> color2Value;
	static{
		color2Value = new LinkedHashMap<String,Object>();
		color2Value.put("Color2 - Red", "Red"); //label, value
		color2Value.put("Color2 - Green", "Green");
		color2Value.put("Color3 - Blue", "Blue");
	}

	public Map<String,Object> getFavColor2Value() {
		return color2Value;
	}

	//Generated by Object array
	public static class Color{
		public String colorLabel;
		public String colorValue;

		public Color(String colorLabel, String colorValue){
			this.colorLabel = colorLabel;
			this.colorValue = colorValue;
		}

		public String getColorLabel(){
			return colorLabel;
		}

		public String getColorValue(){
			return colorValue;
		}

	}

	public Color[] color3List;

	public Color[] getFavColor3Value() {

		color3List = new Color[3];
		color3List[0] = new Color("Color3 - Red", "Red");
		color3List[1] = new Color("Color3 - Green", "Green");
		color3List[2] = new Color("Color3 - Blue", "Blue");

		return color3List;
	}
}
